// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BO.Models;

public partial class Category
{
    public int CategoryId { get; set; }
    [Required (ErrorMessage = "Category name is required.")]
    public string CategoryName { get; set; }

    public string CategoryDescription { get; set; }

    public int? ParentCategoryId { get; set; }
    [Required (ErrorMessage = "Category status is required.")]
    public bool IsActive { get; set; }

    public virtual ICollection<Category> InverseParentCategory { get; set; } = new List<Category>();

    public virtual ICollection<NewsArticle> NewsArticles { get; set; } = new List<NewsArticle>();

    public virtual Category ParentCategory { get; set; }
}