// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BO.Models;

public partial class SystemAccount
{
    public int AccountId { get; set; }
    [Required (ErrorMessage = "AccountName is required.")]
    public string AccountName { get; set; }
    [Required (ErrorMessage = "AccountEmail is required.")]
    public string AccountEmail { get; set; }
    [Required (ErrorMessage = "Role is required.")]
    public int AccountRole { get; set; }
    [Required (ErrorMessage = "AccountPassword is required.")]
    public string AccountPassword { get; set; }

    public virtual ICollection<NewsArticle> NewsArticleCreatedBies { get; set; } = new List<NewsArticle>();

    public virtual ICollection<NewsArticle> NewsArticleUpdatedBies { get; set; } = new List<NewsArticle>();
}