// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BO.Models;

public partial class Tag
{
    public int TagId { get; set; }
    [Required (ErrorMessage = "TagName is required.")]
    public string TagName { get; set; }

    public string Note { get; set; }

    public virtual ICollection<NewsArticle> NewsArticles { get; set; } = new List<NewsArticle>();
}